#from scipy.interpolate import interp1d
from scipy.interpolate import UnivariateSpline
import pickle

## A class for management of the splines associated to the earth matter potential
# This class loads files storing splines for earth density and electron fraction,
# as well as a fictitious linear density profile, used for bug-checking.
# ye_spline is the electron fraction spline, corresponding to the differing 
# chemical composition at different earth radii. It is generated by YeSpline.py and 
# written into ye_spline.p. earth_spline is the earth density spline, generated
# by EarthDensity.py and written to earth_spline.p. line_spline is the test spline,
# generated by LinearSpline.y and written to line_spline.p

class Spline():

	## The constructor
	# Reads in the splines as scipy.interpolate UnivariateSpline objects.
	# These splines are objects which have been 'pickled' using the dill
	# module https://pypi.python.org/pypi/dill
	
	def __init__(self,path="/home/carguelles/work/NeutrinoDecay/neutrino_decay/"):
		self.ye_spline = pickle.load( open( path+"ye_spline.p", "rb" ) )
		self.earth_spline = pickle.load( open( path+"earth_spline.p", "rb" ) )
		self.line_spline = pickle.load( open( path+"line_spline.p", "rb" ) )

	## Returns the electron fraction spline.
	def GetYe(self):
		return self.ye_spline

	## Returns the earth density spline.
	def GetEarth(self):
		return self.earth_spline

	## Returns the test linear earth density spline.
	def GetEarthLine(self):
		return self.line_spline
